In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('final_data.csv')

### We are replacing the missing ages with median rather than deleting them completely

In [3]:
df['Age'] = df.groupby(['Sport', 'Sex'])['Age'].transform(
    lambda x: x.fillna(x.median())
).fillna(df['Age'].median())

df

,index,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,895,512,Shiny Kurisingal Abraham-Wilson,F,19.0,167.0,53.0,India,IND,1984 Summer,1984,Summer,Los Angeles,Athletics,Athletics Women's 800 metres,NaN
1,896,512,Shiny Kurisingal Abraham-Wilson,F,19.0,167.0,53.0,India,IND,1984 Summer,1984,Summer,Los Angeles,Athletics,Athletics Women's 4 x 400 metres Relay,NaN
2,897,512,Shiny Kurisingal Abraham-Wilson,F,23.0,167.0,53.0,India,IND,1988 Summer,1988,Summer,Seoul,Athletics,Athletics Women's 800 metres,NaN
3,898,512,Shiny Kurisingal Abraham-Wilson,F,23.0,167.0,53.0,India,IND,1988 Summer,1988,Summer,Seoul,Athletics,Athletics Women's 4 x 400 metres Relay,NaN
4,899,512,Shiny Kurisingal Abraham-Wilson,F,27.0,167.0,53.0,India,IND,1992 Summer,1992,Summer,Barcelona,Athletics,Athletics Women's 800 metres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
830,264138,132177,Mohammad Anas Yahiya,M,21.0,177.0,69.0,India,IND,2016 Summer,2016,Summer,Rio de Janeiro,Athletics,Athletics Men's 400 metres,NaN
831,264139,132177,Mohammad Anas Yahiya,M,21.0,177.0,69.0,India,IND,2016 Summer,2016,Summer,Rio de Janeiro,Athletics,Athletics Men's 4 x 400 metres Relay,NaN
832,265876,133029,"Thyadathuvilla Chandrapillai ""T. C."" Yohannan",M,29.0,174.0,62.0,India,IND,1976 Summer,1976,Summer,Montreal,Athletics,Athletics Men's Long Jump,NaN
833,270912,135480,Geeta Zutshi,F,23.0,167.0,51.0,India,IND,1980 Summer,1980,Summer,Moskva,Athletics,Athletics Women's 800 metres,NaN
834,270913,135480,Geeta Zutshi,F,27.0,167.0,51.0,India,IND,1984 Summer,1984,Summer,Los Angeles,Athletics,"Athletics Women's 3,000 metres",NaN

## filling missing medal values with string 'no medal'

In [4]:
df['Medal'] = df['Medal'].fillna('No Medal')

In [5]:
df['Medal']

0      No Medal
1      No Medal
2      No Medal
3      No Medal
4      No Medal
         ...
830    No Medal
831    No Medal
832    No Medal
833    No Medal
834    No Medal
Name: Medal, Length: 835, dtype: str

#### stripping the extra sport names

In [6]:

df['Event'] = df.apply(
    lambda row: row['Event'][len(row['Sport']):].strip() 
    if row['Event'].startswith(row['Sport']) else row['Event'], 
    axis=1
)

df['Event']

0                Women's 800 metres
1      Women's 4 x 400 metres Relay
2                Women's 800 metres
3      Women's 4 x 400 metres Relay
4                Women's 800 metres
                   ...
830                Men's 400 metres
831      Men's 4 x 400 metres Relay
832                 Men's Long Jump
833              Women's 800 metres
834            Women's 3,000 metres
Name: Event, Length: 835, dtype: str

# removing dupilicate team names

In [7]:
df[df['Team']!="India"]

,index,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
69,21251,11219,Mahesh Shrinivas Bhupathi,M,38.0,185.0,88.0,India-1,IND,2012 Summer,2012,Summer,London,Tennis,Men's Doubles,No Medal
85,25600,13373,Rohan Bopanna,M,32.0,190.0,87.0,India-1,IND,2012 Summer,2012,Summer,London,Tennis,Men's Doubles,No Medal
388,180125,90518,Leander Adrian Paes,M,39.0,178.0,77.0,India-2,IND,2012 Summer,2012,Summer,London,Tennis,Men's Doubles,No Medal
820,253249,126823,Jagadeesan Vishnuvardhan,M,24.0,188.0,84.0,India-2,IND,2012 Summer,2012,Summer,London,Tennis,Men's Doubles,No Medal

In [8]:
df['Team'] = 'India'

In [9]:
df[df['Team']!="India"]

Empty DataFrame
Columns: [index, ID, Name, Sex, Age, Height, Weight, Team, NOC, Games, Year, Season, City, Sport, Event, Medal]
Index: []

### dropping zero variance coloumns here the country / team always has india drop them

In [10]:
df = df.drop(
    columns=['index', 'NOC', 'Season', 'Games', 'Team']
)

In [11]:
df

,ID,Name,Sex,Age,Height,Weight,Year,City,Sport,Event,Medal
0,512,Shiny Kurisingal Abraham-Wilson,F,19.0,167.0,53.0,1984,Los Angeles,Athletics,Women's 800 metres,No Medal
1,512,Shiny Kurisingal Abraham-Wilson,F,19.0,167.0,53.0,1984,Los Angeles,Athletics,Women's 4 x 400 metres Relay,No Medal
2,512,Shiny Kurisingal Abraham-Wilson,F,23.0,167.0,53.0,1988,Seoul,Athletics,Women's 800 metres,No Medal
3,512,Shiny Kurisingal Abraham-Wilson,F,23.0,167.0,53.0,1988,Seoul,Athletics,Women's 4 x 400 metres Relay,No Medal
4,512,Shiny Kurisingal Abraham-Wilson,F,27.0,167.0,53.0,1992,Barcelona,Athletics,Women's 800 metres,No Medal
...,...,...,...,...,...,...,...,...,...,...,...
830,132177,Mohammad Anas Yahiya,M,21.0,177.0,69.0,2016,Rio de Janeiro,Athletics,Men's 400 metres,No Medal
831,132177,Mohammad Anas Yahiya,M,21.0,177.0,69.0,2016,Rio de Janeiro,Athletics,Men's 4 x 400 metres Relay,No Medal
832,133029,"Thyadathuvilla Chandrapillai ""T. C."" Yohannan",M,29.0,174.0,62.0,1976,Montreal,Athletics,Men's Long Jump,No Medal
833,135480,Geeta Zutshi,F,23.0,167.0,51.0,1980,Moskva,Athletics,Women's 800 metres,No Medal
834,135480,Geeta Zutshi,F,27.0,167.0,51.0,1984,Los Angeles,Athletics,"Women's 3,000 metres",No Medal

In [12]:
## Cleaning athelete names i.e removing (nicknames) and " "(quoted ones)

In [13]:
df['Clean_Name'] = (
    df['Name']
    .str.replace(r'"[^"]*"', '', regex=True)
    .str.replace(r'\([^)]*\)', '', regex=True)
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
)

In [14]:
df

,ID,Name,Sex,Age,Height,Weight,Year,City,Sport,Event,Medal,Clean_Name
0,512,Shiny Kurisingal Abraham-Wilson,F,19.0,167.0,53.0,1984,Los Angeles,Athletics,Women's 800 metres,No Medal,Shiny Kurisingal Abraham-Wilson
1,512,Shiny Kurisingal Abraham-Wilson,F,19.0,167.0,53.0,1984,Los Angeles,Athletics,Women's 4 x 400 metres Relay,No Medal,Shiny Kurisingal Abraham-Wilson
2,512,Shiny Kurisingal Abraham-Wilson,F,23.0,167.0,53.0,1988,Seoul,Athletics,Women's 800 metres,No Medal,Shiny Kurisingal Abraham-Wilson
3,512,Shiny Kurisingal Abraham-Wilson,F,23.0,167.0,53.0,1988,Seoul,Athletics,Women's 4 x 400 metres Relay,No Medal,Shiny Kurisingal Abraham-Wilson
4,512,Shiny Kurisingal Abraham-Wilson,F,27.0,167.0,53.0,1992,Barcelona,Athletics,Women's 800 metres,No Medal,Shiny Kurisingal Abraham-Wilson
...,...,...,...,...,...,...,...,...,...,...,...,...
830,132177,Mohammad Anas Yahiya,M,21.0,177.0,69.0,2016,Rio de Janeiro,Athletics,Men's 400 metres,No Medal,Mohammad Anas Yahiya
831,132177,Mohammad Anas Yahiya,M,21.0,177.0,69.0,2016,Rio de Janeiro,Athletics,Men's 4 x 400 metres Relay,No Medal,Mohammad Anas Yahiya
832,133029,"Thyadathuvilla Chandrapillai ""T. C."" Yohannan",M,29.0,174.0,62.0,1976,Montreal,Athletics,Men's Long Jump,No Medal,Thyadathuvilla Chandrapillai Yohannan
833,135480,Geeta Zutshi,F,23.0,167.0,51.0,1980,Moskva,Athletics,Women's 800 metres,No Medal,Geeta Zutshi
834,135480,Geeta Zutshi,F,27.0,167.0,51.0,1984,Los Angeles,Athletics,"Women's 3,000 metres",No Medal,Geeta Zutshi

In [15]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 835 entries, 0 to 834
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          835 non-null    int64
 1   Name        835 non-null    str
 2   Sex         835 non-null    str
 3   Age         835 non-null    float64
 4   Height      835 non-null    float64
 5   Weight      835 non-null    float64
 6   Year        835 non-null    int64
 7   City        835 non-null    str
 8   Sport       835 non-null    str
 9   Event       835 non-null    str
 10  Medal       835 non-null    str
 11  Clean_Name  835 non-null    str
dtypes: float64(3), int64(2), str(7)
memory usage: 141.9 KB
None

### summarising

In [16]:
with open("df_info.txt", "w") as f:
    df.info(buf=f) # write info to df_info.txt

In [17]:
with open("data_summary.txt", "w") as f:
    f.write("DataFrame Inf0\n")
    df.info(buf=f)

    f.write("\n\nMisssing values\n")
    f.write(df.isnull().sum().to_string())

    f.write("\n\nStatistical Summary\n")
    f.write(df.describe(include='all').to_string()) ## more info about every thing

In [18]:
df.shape

(835, 12)

In [19]:
df.to_csv("data_read_to_use.csv",index=False)